package gdscript.utils

import gdscript.model.GdAnnotation
import gdscript.psi.GdAnnotationTl

/**
 * Do not edit manually
 * Generated by annotationParser.php
 */
object GdAnnotationUtil {

    fun get(annotation: GdAnnotationTl): GdAnnotation? {
        return get(annotation.annotationType.text)
    }

    fun get(name: String): GdAnnotation? {
        return ANNOTATIONS[name.trimStart('@')]
    }

    // Name -> GdAnnotation
    val ANNOTATIONS = mapOf(

    )

}
