package gdscript.utils

import gdscript.GdKeywords

/**
 * Do not edit manually
 * Generated by operandParser.php
 */
object GdOperand {
    
    fun getReturnType(left: String, right: String, operator: String): String {
        val operated = OPERANDS.get(left)?.get(operator) ?: return ""
        val typed = operated.get(right)
        if (typed == null && operator == "[]") {
            return operated.firstOrNull()?.value ?: ""
        }

        return ""
    }

    fun isAllowed(left: String, right: String, operator: String): Boolean {
        val operated = OPERANDS[left]?.get(operator) ?: return false
        return operated.containsKey(right) || operated.containsKey(GdKeywords.VARIANT)
    }

    // Left -> Operand -> Right -> Result
    val OPERANDS = mapOf(

    )

}
