package gdscript.listener

import com.intellij.openapi.diagnostic.thisLogger
import com.intellij.openapi.project.Project
import com.intellij.openapi.startup.ProjectActivity
import com.intellij.openapi.util.Disposer
import com.intellij.openapi.util.io.FileUtil
import com.intellij.openapi.vfs.AsyncFileListener
import com.intellij.openapi.vfs.LocalFileSystem
import com.intellij.openapi.vfs.VirtualFile
import com.intellij.openapi.vfs.VirtualFileManager
import com.intellij.openapi.vfs.newvfs.events.VFileContentChangeEvent
import com.intellij.openapi.vfs.newvfs.events.VFileEvent
import com.intellij.openapi.vfs.newvfs.events.VFilePropertyChangeEvent
import com.jetbrains.rider.godot.community.utils.GodotCommunityUtil
import gdscript.library.GdLibraryUpdater
import gdscript.library.GdSdkFingerprints
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.channels.consumeEach
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.collectLatest
import kotlinx.coroutines.withContext
import java.nio.file.Path
import kotlin.time.Duration.Companion.milliseconds

/**
 * A single user action produces a whole burst of events (installing an addon copies a directory, removing one deletes it
 * file by file), so the requests are collected for a while before the project is scanned.
 */
private val COALESCE_DELAY = 500.milliseconds

/**
 * Keeps the generated GDExtension documentation in sync with the extensions actually installed in the project.
 *
 * The docs are generated by the engine out of the `*.gdextension` files found in the project, so adding, removing or
 * updating an extension while the project is open has to be noticed. The VFS events are only used as a hint that
 * *something* structural happened inside the Godot project: the decision is taken by comparing the current fingerprint
 * of the declarations (see [GdSdkFingerprints]) with the last one seen.
 */
class GdWatchGdExtensionsProjectActivity : ProjectActivity {

    override suspend fun execute(project: Project) {
        // collectLatest: the watcher of the previous base path is torn down before the next one is set up.
        GodotCommunityUtil.getGodotProjectBasePathFlow(project).collectLatest { basePath ->
            if (basePath == null) return@collectLatest
            watchExtensions(project, basePath)
        }
    }

    private suspend fun watchExtensions(project: Project, projectBasePath: Path) {
        // The Godot project directory is not necessarily a content root of the IDE project (in Rider the solution and
        // the Godot project do not have to live in the same folder), and without a watched root the local file system
        // reports nothing at all - which is exactly what "an addon copied in outside the IDE" looks like.
        val watchRequest = LocalFileSystem.getInstance().addRootToWatch(projectBasePath.toString(), true)
        val disposable = Disposer.newDisposable("GdScript GDExtensions watcher")
        try {
            thisLogger().info("Watching $projectBasePath for GDExtension changes")
            // Conflated: while a regeneration is being prepared or is running, all the requests collapse into a single one.
            val requests = Channel<Unit>(Channel.CONFLATED)
            val listener = GdExtensionsFileListener(projectBasePath.toString()) { requests.trySend(Unit) }
            VirtualFileManager.getInstance().addAsyncFileListener(listener, disposable)

            processRequests(project, projectBasePath, requests)
        } finally {
            Disposer.dispose(disposable)
            watchRequest?.let { LocalFileSystem.getInstance().removeWatchedRoot(it) }
        }
    }

    /**
     * The requests are deliberately coarse - a single directory event stands for its whole subtree - so most of them do
     * not concern the extensions at all and are dropped here, before anything heavier than a scan is started.
     */
    private suspend fun processRequests(project: Project, projectBasePath: Path, requests: Channel<Unit>) {
        var knownExtensions: String? = null

        requests.consumeEach {
            delay(COALESCE_DELAY)
            // Everything that happened while waiting is covered by the scan below.
            var pending = requests.tryReceive()
            while (pending.isSuccess) {
                pending = requests.tryReceive()
            }

            if (project.isDisposed) return
            val godotPath = GodotCommunityUtil.getGodotExecutablePath(project) ?: return@consumeEach

            val extensions = withContext(Dispatchers.IO) { GdSdkFingerprints.ofExtensionDeclarations(projectBasePath) }
            if (extensions == knownExtensions) return@consumeEach
            knownExtensions = extensions

            thisLogger().info("The GDExtensions of $projectBasePath may have changed, checking the generated documentation")
            GdLibraryUpdater.getInstance(project).scheduleSdkLoad(projectBasePath, godotPath)
        }
    }
}

private class GdExtensionsFileListener(
    private val projectBasePath: String,
    private val onChange: () -> Unit,
) : AsyncFileListener {

    override fun prepareChange(events: MutableList<out VFileEvent>): AsyncFileListener.ChangeApplier? {
        if (events.none { GdExtensionsChangeDetector.mayChangeExtensions(projectBasePath, it) }) return null

        return object : AsyncFileListener.ChangeApplier {
            override fun afterVfsChange() {
                onChange()
            }
        }
    }
}

/**
 * Tells whether a VFS event may have changed the set of GDExtensions installed in the project. Path-based on purpose:
 * `prepareChange` is called for every change in the IDE and must stay cheap, a deletion invalidates the [VirtualFile]
 * and a creation has none yet.
 *
 * Whether the extensions really changed is decided by [GdSdkFingerprints.ofExtensionDeclarations], so this is only a
 * cheap filter and is allowed to be over-eager: what it must not do is miss a change.
 */
object GdExtensionsChangeDetector {

    /** Rewritten by the editor whenever the set of loaded extensions changes. */
    private const val EXTENSION_LIST_FILE_NAME = "extension_list.cfg"

    fun mayChangeExtensions(projectBasePath: String, event: VFileEvent): Boolean {
        val path = event.path
        // The VFS reports the creation or the deletion of a whole subtree as a single event for its topmost directory
        // (the children of a new folder are not even loaded yet), so an event on an ancestor of the Godot project
        // directory - the project directory itself included - stands for the extensions inside it as well.
        val insideProject = FileUtil.isAncestor(projectBasePath, path, false)
        if (!insideProject && !FileUtil.isAncestor(path, projectBasePath, false)) return false
        if (insideProject && isInSkippedDirectory(projectBasePath, path)) return false

        // A content change matters for the declarations only: everything else in the project is written all the time
        // (builds, imports, the editor itself) and cannot add or remove an extension.
        if (event is VFileContentChangeEvent) return isExtensionDefinitionPath(path)

        if (event is VFilePropertyChangeEvent) {
            if (event.propertyName != VirtualFile.PROP_NAME) return false
            // A file renamed away from *.gdextension: only its previous name matches.
            val oldName = event.oldValue as? String
            return isExtensionDefinitionPath(path) || (oldName != null && isExtensionDefinitionPath(oldName))
        }

        // What is left is a creation, a deletion, a copy or a move: any of those may bring in or take away a
        // declaration, whether the event describes a file or the directory holding it.
        return true
    }

    fun isExtensionDefinitionPath(path: String): Boolean {
        val name = path.substringAfterLast('/')
        return name.endsWith(GdSdkFingerprints.GDEXTENSION_SUFFIX, ignoreCase = true)
               || name.equals(EXTENSION_LIST_FILE_NAME, ignoreCase = true)
    }

    /** Skips exactly the directories the fingerprint does not scan either (see [GdSdkFingerprints.SKIPPED_DIRECTORY_NAMES]). */
    fun isInSkippedDirectory(projectBasePath: String, path: String): Boolean {
        val relativePath = FileUtil.getRelativePath(projectBasePath, path, '/') ?: return false
        return relativePath.splitToSequence('/').any { it in GdSdkFingerprints.SKIPPED_DIRECTORY_NAMES }
    }
}
