package gdscript.run;

import com.intellij.openapi.fileChooser.FileChooserDescriptorFactory;
import com.intellij.openapi.options.SettingsEditor;
import com.intellij.openapi.ui.LabeledComponent;
import com.intellij.openapi.ui.TextBrowseFolderListener;
import com.intellij.openapi.ui.TextFieldWithBrowseButton;
import com.intellij.openapi.util.SystemInfo;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import gdscript.GdScriptBundle;
import org.jetbrains.annotations.NotNull;

import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JTextField;
import java.awt.Dimension;
import java.awt.Insets;

public class GdSettingsEditor extends SettingsEditor<GdRunConfiguration> {

  private final JPanel myPanel;
  private final LabeledComponent<TextFieldWithBrowseButton> godotExe;
  private final LabeledComponent<TextFieldWithBrowseButton> tscn;
  private final LabeledComponent<JTextField> arguments;
  private final JCheckBox debugShapes;
  private final JCheckBox debugPaths;

  public GdSettingsEditor() {
    {
      godotExe = new LabeledComponent<>();
      tscn = new LabeledComponent<>();
      arguments = new LabeledComponent<>();
      TextFieldWithBrowseButton godotField = new TextFieldWithBrowseButton();
      godotField.setText("");
      godotField.setToolTipText(GdScriptBundle.message("settings.path.to.godot.executable"));
      godotField.addBrowseFolderListener(new TextBrowseFolderListener(
        SystemInfo.isWindows ?
        FileChooserDescriptorFactory.createSingleFileDescriptor("exe") :
        FileChooserDescriptorFactory.createSingleFileOrExecutableAppDescriptor()
      ));
      godotExe.setComponent(godotField);

      TextFieldWithBrowseButton tscnField = new TextFieldWithBrowseButton();
      tscnField.setText("Node.tscn");
      tscnField.setToolTipText("Node.tscn");
      tscnField.addBrowseFolderListener(new TextBrowseFolderListener(
        FileChooserDescriptorFactory.createSingleFileDescriptor("tscn")
      ));
      tscn.setComponent(tscnField);

      JTextField argumentsField = new JTextField();
      argumentsField.setText(GdScriptBundle.message("settings.options"));
      argumentsField.setToolTipText(GdScriptBundle.message("settings.options"));
      arguments.setComponent(argumentsField);
    }
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myPanel = new JPanel();
      myPanel.setLayout(new GridLayoutManager(6, 4, new Insets(0, 0, 0, 0), -1, -1));
      final Spacer spacer1 = new Spacer();
      myPanel.add(spacer1, new GridConstraints(5, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                               GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      tscn.setLabelLocation("West");
      tscn.setText("Scene file");
      myPanel.add(tscn, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null,
                                            new Dimension(-1, 20), null, 0, false));
      godotExe.setLabelLocation("West");
      godotExe.setText("Godot Executable");
      myPanel.add(godotExe, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null,
                                                new Dimension(-1, 20), null, 0, false));
      debugShapes = new JCheckBox();
      debugShapes.setSelected(false);
      debugShapes.setText("Visible Collision Shapes");
      myPanel.add(debugShapes, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                   GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                   GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      debugPaths = new JCheckBox();
      debugPaths.setText("Visible Paths");
      myPanel.add(debugPaths, new GridConstraints(4, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                  GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                  GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      arguments.setLabelLocation("West");
      arguments.setText("Options");
      myPanel.add(arguments, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                 GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                 GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null,
                                                 new Dimension(-1, 20), null, 0, false));
    }
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myPanel; }

  @Override
  public void resetEditorFrom(GdRunConfiguration gdRunConfiguration) {
    godotExe.getComponent().setText(gdRunConfiguration.getGodotExe());
    tscn.getComponent().setText(gdRunConfiguration.getTscn());
    arguments.getComponent().setText(gdRunConfiguration.getArguments());
    debugShapes.setSelected(gdRunConfiguration.getDebugShapes());
    debugPaths.setSelected(gdRunConfiguration.getDebugPaths());
  }

  @Override
  public void applyEditorTo(GdRunConfiguration gdRunConfiguration) {
    gdRunConfiguration.setGodotExe(godotExe.getComponent().getText());
    gdRunConfiguration.setTscn(tscn.getComponent().getText());
    gdRunConfiguration.setArguments(arguments.getComponent().getText());
    gdRunConfiguration.setDebugShapes(debugShapes.isSelected());
    gdRunConfiguration.setDebugPaths(debugPaths.isSelected());
  }

  @Override
  public @NotNull JComponent createEditor() {
    return myPanel;
  }
}
