//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "FrontendGodotModel.h"


#include "FrontendGodotRoot/FrontendGodotRoot.h"

#ifdef _MSC_VER
#pragma warning( push )
#pragma warning( disable:4250 )
#pragma warning( disable:4307 )
#pragma warning( disable:4267 )
#pragma warning( disable:4244 )
#pragma warning( disable:4100 )
#endif

namespace JetBrains {
namespace GodotPlugin {
// companion

FrontendGodotModel::FrontendGodotModelSerializersOwner const FrontendGodotModel::serializersOwner;

void FrontendGodotModel::FrontendGodotModelSerializersOwner::registerSerializersCore(rd::Serializers const& serializers) const
{
}

void FrontendGodotModel::connect(rd::Lifetime lifetime, rd::IProtocol const * protocol)
{
    FrontendGodotRoot::serializersOwner.registry(protocol->get_serializers());
    
    identify(*(protocol->get_identity()), rd::RdId::Null().mix("FrontendGodotModel"));
    bind(lifetime, protocol, "FrontendGodotModel");
}

// constants
constexpr rd::wstring_view FrontendGodotModel::portFilename;
constexpr rd::wstring_view FrontendGodotModel::portKey;
constexpr rd::wstring_view FrontendGodotModel::modelHashKey;
// initializer
void FrontendGodotModel::initialize()
{
    serializationHash = -308188172126286094L;
}
// primary ctor
FrontendGodotModel::FrontendGodotModel(rd::RdSignal<std::wstring, rd::Polymorphic<std::wstring>> openInGodot_, rd::RdSignal<std::wstring, rd::Polymorphic<std::wstring>> openInRider_, rd::RdSignal<std::wstring, rd::Polymorphic<std::wstring>> currentSceneChange_) :
rd::RdExtBase()
,openInGodot_(std::move(openInGodot_)), openInRider_(std::move(openInRider_)), currentSceneChange_(std::move(currentSceneChange_))
{
    initialize();
}
// secondary constructor
// default ctors and dtors
FrontendGodotModel::FrontendGodotModel()
{
    initialize();
}
// reader
// writer
// virtual init
void FrontendGodotModel::init(rd::Lifetime lifetime) const
{
    rd::RdExtBase::init(lifetime);
    bindPolymorphic(openInGodot_, lifetime, this, "openInGodot");
    bindPolymorphic(openInRider_, lifetime, this, "openInRider");
    bindPolymorphic(currentSceneChange_, lifetime, this, "currentSceneChange");
}
// identify
void FrontendGodotModel::identify(const rd::Identities &identities, rd::RdId const &id) const
{
    rd::RdBindableBase::identify(identities, id);
    identifyPolymorphic(openInGodot_, identities, id.mix(".openInGodot"));
    identifyPolymorphic(openInRider_, identities, id.mix(".openInRider"));
    identifyPolymorphic(currentSceneChange_, identities, id.mix(".currentSceneChange"));
}
// getters
rd::ISource<std::wstring> const & FrontendGodotModel::get_openInGodot() const
{
    
    /**
     * Opens the given file in Godot. For files such as shaders, scenes,... it will open them inside the scene tree, shader editor... For files that cannot be opened, will be highlighted inside the filesystem dock.
     */
    return openInGodot_;
}
rd::ISignal<std::wstring> const & FrontendGodotModel::get_openInRider() const
{
    
    /**
     * Opens a given file in Rider editor.
     */
    return openInRider_;
}
rd::ISignal<std::wstring> const & FrontendGodotModel::get_currentSceneChange() const
{
    
    /**
     * Used for syncing what scene Godot has currently opened.
     */
    return currentSceneChange_;
}
// intern
// equals trait
// equality operators
bool operator==(const FrontendGodotModel &lhs, const FrontendGodotModel &rhs) {
    return &lhs == &rhs;
}
bool operator!=(const FrontendGodotModel &lhs, const FrontendGodotModel &rhs){
    return !(lhs == rhs);
}
// hash code trait
// type name trait
// static type name trait
// polymorphic to string
std::string FrontendGodotModel::toString() const
{
    std::string res = "FrontendGodotModel\n";
    res += "\topenInGodot = ";
    res += rd::to_string(openInGodot_);
    res += '\n';
    res += "\topenInRider = ";
    res += rd::to_string(openInRider_);
    res += '\n';
    res += "\tcurrentSceneChange = ";
    res += rd::to_string(currentSceneChange_);
    res += '\n';
    return res;
}
// external to string
std::string to_string(const FrontendGodotModel & value)
{
    return value.toString();
}
}
}

#ifdef _MSC_VER
#pragma warning( pop )
#endif

