//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#ifndef FRONTENDGODOTMODEL_H
#define FRONTENDGODOTMODEL_H


#include "protocol/Protocol.h"
#include "types/DateTime.h"
#include "impl/RdSignal.h"
#include "impl/RdProperty.h"
#include "impl/RdList.h"
#include "impl/RdSet.h"
#include "impl/RdMap.h"
#include "base/ISerializersOwner.h"
#include "base/IUnknownInstance.h"
#include "serialization/ISerializable.h"
#include "serialization/Polymorphic.h"
#include "serialization/NullableSerializer.h"
#include "serialization/ArraySerializer.h"
#include "serialization/InternedSerializer.h"
#include "serialization/SerializationCtx.h"
#include "serialization/Serializers.h"
#include "ext/RdExtBase.h"
#include "task/RdCall.h"
#include "task/RdEndpoint.h"
#include "task/RdSymmetricCall.h"
#include "std/to_string.h"
#include "std/hash.h"
#include "std/allocator.h"
#include "util/enum.h"
#include "util/gen_util.h"

#include <cstring>
#include <cstdint>
#include <vector>
#include <ctime>

#include "thirdparty.hpp"
#include "instantiations_FrontendGodotRoot.h"



#ifdef _MSC_VER
#pragma warning( push )
#pragma warning( disable:4250 )
#pragma warning( disable:4307 )
#pragma warning( disable:4267 )
#pragma warning( disable:4244 )
#pragma warning( disable:4100 )
#endif

namespace JetBrains {
namespace GodotPlugin {

class FrontendGodotModel : public rd::RdExtBase {

public:
    struct FrontendGodotModelSerializersOwner final : public rd::ISerializersOwner {
        void registerSerializersCore(rd::Serializers const& serializers) const override;
    };
    
    static const FrontendGodotModelSerializersOwner serializersOwner;
    
    

public:
    void connect(rd::Lifetime lifetime, rd::IProtocol const * protocol);
    

private:
    // custom serializers

public:
    // constants
    static constexpr rd::wstring_view portFilename{L"rider_ide_server.cfg", 20};
    static constexpr rd::wstring_view portKey{L"port", 4};
    static constexpr rd::wstring_view modelHashKey{L"modelHash", 9};

protected:
    // fields
    rd::RdSignal<std::wstring, rd::Polymorphic<std::wstring>> openInGodot_;
    rd::RdSignal<std::wstring, rd::Polymorphic<std::wstring>> openInRider_;
    rd::RdSignal<std::wstring, rd::Polymorphic<std::wstring>> currentSceneChange_;
    

private:
    // initializer
    void initialize();

public:
    // primary ctor
    FrontendGodotModel(rd::RdSignal<std::wstring, rd::Polymorphic<std::wstring>> openInGodot_, rd::RdSignal<std::wstring, rd::Polymorphic<std::wstring>> openInRider_, rd::RdSignal<std::wstring, rd::Polymorphic<std::wstring>> currentSceneChange_);
    
    // default ctors and dtors
    
    FrontendGodotModel();
    
    FrontendGodotModel(FrontendGodotModel &&) = delete;
    
    FrontendGodotModel& operator=(FrontendGodotModel &&) = delete;
    
    virtual ~FrontendGodotModel() = default;
    
    // reader
    
    // writer
    
    // virtual init
    void init(rd::Lifetime lifetime) const override;
    
    // identify
    void identify(const rd::Identities &identities, rd::RdId const &id) const override;
    
    // getters
    rd::ISource<std::wstring> const & get_openInGodot() const;
    rd::ISignal<std::wstring> const & get_openInRider() const;
    rd::ISignal<std::wstring> const & get_currentSceneChange() const;
    
    // intern

private:
    // equals trait

public:
    // equality operators
    friend bool operator==(const FrontendGodotModel &lhs, const FrontendGodotModel &rhs);
    friend bool operator!=(const FrontendGodotModel &lhs, const FrontendGodotModel &rhs);
    // hash code trait
    // type name trait
    // static type name trait

private:
    // polymorphic to string
    std::string toString() const override;

public:
    // external to string
    friend std::string to_string(const FrontendGodotModel & value);
};

}
}

#ifdef _MSC_VER
#pragma warning( pop )
#endif



#endif // FRONTENDGODOTMODEL_H
