extends Material
class_name BaseMaterial3D

const TEXTURE_ALBEDO = 0;
const TEXTURE_METALLIC = 1;
const TEXTURE_ROUGHNESS = 2;
const TEXTURE_EMISSION = 3;
const TEXTURE_NORMAL = 4;
const TEXTURE_RIM = 5;
const TEXTURE_CLEARCOAT = 6;
const TEXTURE_FLOWMAP = 7;
const TEXTURE_AMBIENT_OCCLUSION = 8;
const TEXTURE_HEIGHTMAP = 9;
const TEXTURE_SUBSURFACE_SCATTERING = 10;
const TEXTURE_SUBSURFACE_TRANSMITTANCE = 11;
const TEXTURE_BACKLIGHT = 12;
const TEXTURE_REFRACTION = 13;
const TEXTURE_DETAIL_MASK = 14;
const TEXTURE_DETAIL_ALBEDO = 15;
const TEXTURE_DETAIL_NORMAL = 16;
const TEXTURE_ORM = 17;
const TEXTURE_MAX = 18;
const TEXTURE_FILTER_NEAREST = 0;
const TEXTURE_FILTER_LINEAR = 1;
const TEXTURE_FILTER_NEAREST_WITH_MIPMAPS = 2;
const TEXTURE_FILTER_LINEAR_WITH_MIPMAPS = 3;
const TEXTURE_FILTER_NEAREST_WITH_MIPMAPS_ANISOTROPIC = 4;
const TEXTURE_FILTER_LINEAR_WITH_MIPMAPS_ANISOTROPIC = 5;
const TEXTURE_FILTER_MAX = 6;
const DETAIL_UV_1 = 0;
const DETAIL_UV_2 = 1;
const TRANSPARENCY_DISABLED = 0;
const TRANSPARENCY_ALPHA = 1;
const TRANSPARENCY_ALPHA_SCISSOR = 2;
const TRANSPARENCY_ALPHA_HASH = 3;
const TRANSPARENCY_ALPHA_DEPTH_PRE_PASS = 4;
const TRANSPARENCY_MAX = 5;
const SHADING_MODE_UNSHADED = 0;
const SHADING_MODE_PER_PIXEL = 1;
const SHADING_MODE_PER_VERTEX = 2;
const SHADING_MODE_MAX = 3;
const FEATURE_EMISSION = 0;
const FEATURE_NORMAL_MAPPING = 1;
const FEATURE_RIM = 2;
const FEATURE_CLEARCOAT = 3;
const FEATURE_ANISOTROPY = 4;
const FEATURE_AMBIENT_OCCLUSION = 5;
const FEATURE_HEIGHT_MAPPING = 6;
const FEATURE_SUBSURFACE_SCATTERING = 7;
const FEATURE_SUBSURFACE_TRANSMITTANCE = 8;
const FEATURE_BACKLIGHT = 9;
const FEATURE_REFRACTION = 10;
const FEATURE_DETAIL = 11;
const FEATURE_MAX = 12;
const BLEND_MODE_MIX = 0;
const BLEND_MODE_ADD = 1;
const BLEND_MODE_SUB = 2;
const BLEND_MODE_MUL = 3;
const ALPHA_ANTIALIASING_OFF = 0;
const ALPHA_ANTIALIASING_ALPHA_TO_COVERAGE = 1;
const ALPHA_ANTIALIASING_ALPHA_TO_COVERAGE_AND_TO_ONE = 2;
const DEPTH_DRAW_OPAQUE_ONLY = 0;
const DEPTH_DRAW_ALWAYS = 1;
const DEPTH_DRAW_DISABLED = 2;
const CULL_BACK = 0;
const CULL_FRONT = 1;
const CULL_DISABLED = 2;
const FLAG_DISABLE_DEPTH_TEST = 0;
const FLAG_ALBEDO_FROM_VERTEX_COLOR = 1;
const FLAG_SRGB_VERTEX_COLOR = 2;
const FLAG_USE_POINT_SIZE = 3;
const FLAG_FIXED_SIZE = 4;
const FLAG_BILLBOARD_KEEP_SCALE = 5;
const FLAG_UV1_USE_TRIPLANAR = 6;
const FLAG_UV2_USE_TRIPLANAR = 7;
const FLAG_UV1_USE_WORLD_TRIPLANAR = 8;
const FLAG_UV2_USE_WORLD_TRIPLANAR = 9;
const FLAG_AO_ON_UV2 = 10;
const FLAG_EMISSION_ON_UV2 = 11;
const FLAG_ALBEDO_TEXTURE_FORCE_SRGB = 12;
const FLAG_DONT_RECEIVE_SHADOWS = 13;
const FLAG_DISABLE_AMBIENT_LIGHT = 14;
const FLAG_USE_SHADOW_TO_OPACITY = 15;
const FLAG_USE_TEXTURE_REPEAT = 16;
const FLAG_INVERT_HEIGHTMAP = 17;
const FLAG_SUBSURFACE_MODE_SKIN = 18;
const FLAG_PARTICLE_TRAILS_MODE = 19;
const FLAG_MAX = 20;
const DIFFUSE_BURLEY = 0;
const DIFFUSE_LAMBERT = 1;
const DIFFUSE_LAMBERT_WRAP = 2;
const DIFFUSE_TOON = 3;
const SPECULAR_SCHLICK_GGX = 0;
const SPECULAR_BLINN = 1;
const SPECULAR_PHONG = 2;
const SPECULAR_TOON = 3;
const SPECULAR_DISABLED = 4;
const BILLBOARD_DISABLED = 0;
const BILLBOARD_ENABLED = 1;
const BILLBOARD_FIXED_Y = 2;
const BILLBOARD_PARTICLES = 3;
const TEXTURE_CHANNEL_RED = 0;
const TEXTURE_CHANNEL_GREEN = 1;
const TEXTURE_CHANNEL_BLUE = 2;
const TEXTURE_CHANNEL_ALPHA = 3;
const TEXTURE_CHANNEL_GRAYSCALE = 4;
const EMISSION_OP_ADD = 0;
const EMISSION_OP_MULTIPLY = 1;
const DISTANCE_FADE_DISABLED = 0;
const DISTANCE_FADE_PIXEL_ALPHA = 1;
const DISTANCE_FADE_PIXEL_DITHER = 2;
const DISTANCE_FADE_OBJECT_DITHER = 3;

var albedo_color: Color setget set_albedo, get_albedo;
var albedo_tex_force_srgb: bool setget set_flag, get_flag;
var albedo_texture: Texture2D setget set_texture, get_texture;
var alpha_antialiasing_edge: float setget set_alpha_antialiasing_edge, get_alpha_antialiasing_edge;
var alpha_antialiasing_mode: int setget set_alpha_antialiasing, get_alpha_antialiasing;
var alpha_hash_scale: float setget set_alpha_hash_scale, get_alpha_hash_scale;
var alpha_scissor_threshold: float setget set_alpha_scissor_threshold, get_alpha_scissor_threshold;
var anisotropy: float setget set_anisotropy, get_anisotropy;
var anisotropy_enabled: bool setget set_feature, get_feature;
var anisotropy_flowmap: Texture2D setget set_texture, get_texture;
var ao_enabled: bool setget set_feature, get_feature;
var ao_light_affect: float setget set_ao_light_affect, get_ao_light_affect;
var ao_on_uv2: bool setget set_flag, get_flag;
var ao_texture: Texture2D setget set_texture, get_texture;
var ao_texture_channel: int setget set_ao_texture_channel, get_ao_texture_channel;
var backlight: Color setget set_backlight, get_backlight;
var backlight_enabled: bool setget set_feature, get_feature;
var backlight_texture: Texture2D setget set_texture, get_texture;
var billboard_keep_scale: bool setget set_flag, get_flag;
var billboard_mode: int setget set_billboard_mode, get_billboard_mode;
var blend_mode: int setget set_blend_mode, get_blend_mode;
var clearcoat: float setget set_clearcoat, get_clearcoat;
var clearcoat_enabled: bool setget set_feature, get_feature;
var clearcoat_gloss: float setget set_clearcoat_gloss, get_clearcoat_gloss;
var clearcoat_texture: Texture2D setget set_texture, get_texture;
var cull_mode: int setget set_cull_mode, get_cull_mode;
var depth_draw_mode: int setget set_depth_draw_mode, get_depth_draw_mode;
var detail_albedo: Texture2D setget set_texture, get_texture;
var detail_blend_mode: int setget set_detail_blend_mode, get_detail_blend_mode;
var detail_enabled: bool setget set_feature, get_feature;
var detail_mask: Texture2D setget set_texture, get_texture;
var detail_normal: Texture2D setget set_texture, get_texture;
var detail_uv_layer: int setget set_detail_uv, get_detail_uv;
var diffuse_mode: int setget set_diffuse_mode, get_diffuse_mode;
var disable_ambient_light: bool setget set_flag, get_flag;
var disable_receive_shadows: bool setget set_flag, get_flag;
var distance_fade_max_distance: float setget set_distance_fade_max_distance, get_distance_fade_max_distance;
var distance_fade_min_distance: float setget set_distance_fade_min_distance, get_distance_fade_min_distance;
var distance_fade_mode: int setget set_distance_fade, get_distance_fade;
var emission: Color setget set_emission, get_emission;
var emission_enabled: bool setget set_feature, get_feature;
var emission_energy: float setget set_emission_energy, get_emission_energy;
var emission_on_uv2: bool setget set_flag, get_flag;
var emission_operator: int setget set_emission_operator, get_emission_operator;
var emission_texture: Texture2D setget set_texture, get_texture;
var fixed_size: bool setget set_flag, get_flag;
var grow: bool setget set_grow_enabled, is_grow_enabled;
var grow_amount: float setget set_grow, get_grow;
var heightmap_deep_parallax: bool setget set_heightmap_deep_parallax, is_heightmap_deep_parallax_enabled;
var heightmap_enabled: bool setget set_feature, get_feature;
var heightmap_flip_binormal: bool setget set_heightmap_deep_parallax_flip_binormal, get_heightmap_deep_parallax_flip_binormal;
var heightmap_flip_tangent: bool setget set_heightmap_deep_parallax_flip_tangent, get_heightmap_deep_parallax_flip_tangent;
var heightmap_flip_texture: bool setget set_flag, get_flag;
var heightmap_max_layers: int setget set_heightmap_deep_parallax_max_layers, get_heightmap_deep_parallax_max_layers;
var heightmap_min_layers: int setget set_heightmap_deep_parallax_min_layers, get_heightmap_deep_parallax_min_layers;
var heightmap_scale: float setget set_heightmap_scale, get_heightmap_scale;
var heightmap_texture: Texture2D setget set_texture, get_texture;
var metallic: float setget set_metallic, get_metallic;
var metallic_specular: float setget set_specular, get_specular;
var metallic_texture: Texture2D setget set_texture, get_texture;
var metallic_texture_channel: int setget set_metallic_texture_channel, get_metallic_texture_channel;
var no_depth_test: bool setget set_flag, get_flag;
var normal_enabled: bool setget set_feature, get_feature;
var normal_scale: float setget set_normal_scale, get_normal_scale;
var normal_texture: Texture2D setget set_texture, get_texture;
var orm_texture: Texture2D setget set_texture, get_texture;
var particles_anim_h_frames: int setget set_particles_anim_h_frames, get_particles_anim_h_frames;
var particles_anim_loop: bool setget set_particles_anim_loop, get_particles_anim_loop;
var particles_anim_v_frames: int setget set_particles_anim_v_frames, get_particles_anim_v_frames;
var point_size: float setget set_point_size, get_point_size;
var proximity_fade_distance: float setget set_proximity_fade_distance, get_proximity_fade_distance;
var proximity_fade_enable: bool setget set_proximity_fade, is_proximity_fade_enabled;
var refraction_enabled: bool setget set_feature, get_feature;
var refraction_scale: float setget set_refraction, get_refraction;
var refraction_texture: Texture2D setget set_texture, get_texture;
var refraction_texture_channel: int setget set_refraction_texture_channel, get_refraction_texture_channel;
var rim: float setget set_rim, get_rim;
var rim_enabled: bool setget set_feature, get_feature;
var rim_texture: Texture2D setget set_texture, get_texture;
var rim_tint: float setget set_rim_tint, get_rim_tint;
var roughness: float setget set_roughness, get_roughness;
var roughness_texture: Texture2D setget set_texture, get_texture;
var roughness_texture_channel: int setget set_roughness_texture_channel, get_roughness_texture_channel;
var shading_mode: int setget set_shading_mode, get_shading_mode;
var shadow_to_opacity: bool setget set_flag, get_flag;
var specular_mode: int setget set_specular_mode, get_specular_mode;
var subsurf_scatter_enabled: bool setget set_feature, get_feature;
var subsurf_scatter_skin_mode: bool setget set_flag, get_flag;
var subsurf_scatter_strength: float setget set_subsurface_scattering_strength, get_subsurface_scattering_strength;
var subsurf_scatter_texture: Texture2D setget set_texture, get_texture;
var subsurf_scatter_transmittance_boost: float setget set_transmittance_boost, get_transmittance_boost;
var subsurf_scatter_transmittance_color: Color setget set_transmittance_color, get_transmittance_color;
var subsurf_scatter_transmittance_depth: float setget set_transmittance_depth, get_transmittance_depth;
var subsurf_scatter_transmittance_enabled: bool setget set_feature, get_feature;
var subsurf_scatter_transmittance_texture: Texture2D setget set_texture, get_texture;
var texture_filter: int setget set_texture_filter, get_texture_filter;
var texture_repeat: bool setget set_flag, get_flag;
var transparency: int setget set_transparency, get_transparency;
var use_particle_trails: bool setget set_flag, get_flag;
var use_point_size: bool setget set_flag, get_flag;
var uv1_offset: Vector3 setget set_uv1_offset, get_uv1_offset;
var uv1_scale: Vector3 setget set_uv1_scale, get_uv1_scale;
var uv1_triplanar: bool setget set_flag, get_flag;
var uv1_triplanar_sharpness: float setget set_uv1_triplanar_blend_sharpness, get_uv1_triplanar_blend_sharpness;
var uv1_world_triplanar: bool setget set_flag, get_flag;
var uv2_offset: Vector3 setget set_uv2_offset, get_uv2_offset;
var uv2_scale: Vector3 setget set_uv2_scale, get_uv2_scale;
var uv2_triplanar: bool setget set_flag, get_flag;
var uv2_triplanar_sharpness: float setget set_uv2_triplanar_blend_sharpness, get_uv2_triplanar_blend_sharpness;
var uv2_world_triplanar: bool setget set_flag, get_flag;
var vertex_color_is_srgb: bool setget set_flag, get_flag;
var vertex_color_use_as_albedo: bool setget set_flag, get_flag;

func get_feature(feature: int) -> bool:
    pass;

func get_flag(flag: int) -> bool:
    pass;

func get_texture(param: int) -> Texture2D:
    pass;

func set_feature(feature: int, enable: bool) -> void:
    pass;

func set_flag(flag: int, enable: bool) -> void:
    pass;

func set_texture(param: int, texture: Texture2D) -> void:
    pass;

