#brief Custom generator of previews.
#desc Custom code to generate previews. Please check [code]file_dialog/thumbnail_size[/code] in [EditorSettings] to find out the right size to do previews at.
class_name EditorResourcePreviewGenerator




#desc If this function returns [code]true[/code], the generator will call [method _generate] or [method _generate_from_path] for small previews as well.
#desc By default, it returns [code]false[/code].
virtual const func _can_generate_small_preview() -> bool:
	pass;

#desc Generate a preview from a given resource with the specified size. This must always be implemented.
#desc Returning an empty texture is an OK way to fail and let another generator take care.
#desc Care must be taken because this function is always called from a thread (not the main thread).
virtual const func _generate(resource: Resource, size: Vector2i) -> Texture2D:
	pass;

#desc Generate a preview directly from a path with the specified size. Implementing this is optional, as default code will load and call [method _generate].
#desc Returning an empty texture is an OK way to fail and let another generator take care.
#desc Care must be taken because this function is always called from a thread (not the main thread).
virtual const func _generate_from_path(path: String, size: Vector2i) -> Texture2D:
	pass;

#desc If this function returns [code]true[/code], the generator will automatically generate the small previews from the normal preview texture generated by the methods [method _generate] or [method _generate_from_path].
#desc By default, it returns [code]false[/code].
virtual const func _generate_small_preview_automatically() -> bool:
	pass;

#desc Returns [code]true[/code] if your generator supports the resource of type [param type].
virtual const func _handles(type: String) -> bool:
	pass;


