extends Resource
class_name Environment

const BG_CLEAR_COLOR = 0;
const BG_COLOR = 1;
const BG_SKY = 2;
const BG_CANVAS = 3;
const BG_KEEP = 4;
const BG_CAMERA_FEED = 5;
const BG_MAX = 6;
const AMBIENT_SOURCE_BG = 0;
const AMBIENT_SOURCE_DISABLED = 1;
const AMBIENT_SOURCE_COLOR = 2;
const AMBIENT_SOURCE_SKY = 3;
const REFLECTION_SOURCE_BG = 0;
const REFLECTION_SOURCE_DISABLED = 1;
const REFLECTION_SOURCE_SKY = 2;
const TONE_MAPPER_LINEAR = 0;
const TONE_MAPPER_REINHARDT = 1;
const TONE_MAPPER_FILMIC = 2;
const TONE_MAPPER_ACES = 3;
const GLOW_BLEND_MODE_ADDITIVE = 0;
const GLOW_BLEND_MODE_SCREEN = 1;
const GLOW_BLEND_MODE_SOFTLIGHT = 2;
const GLOW_BLEND_MODE_REPLACE = 3;
const GLOW_BLEND_MODE_MIX = 4;
const SDFGI_CASCADES_4 = 0;
const SDFGI_CASCADES_6 = 1;
const SDFGI_CASCADES_8 = 2;
const SDFGI_Y_SCALE_DISABLED = 0;
const SDFGI_Y_SCALE_75_PERCENT = 1;
const SDFGI_Y_SCALE_50_PERCENT = 2;
const VOLUMETRIC_FOG_SHADOW_FILTER_DISABLED = 0;
const VOLUMETRIC_FOG_SHADOW_FILTER_LOW = 1;
const VOLUMETRIC_FOG_SHADOW_FILTER_MEDIUM = 2;
const VOLUMETRIC_FOG_SHADOW_FILTER_HIGH = 3;

var adjustment_brightness: float setget set_adjustment_brightness, get_adjustment_brightness;
var adjustment_color_correction: Texture setget set_adjustment_color_correction, get_adjustment_color_correction;
var adjustment_contrast: float setget set_adjustment_contrast, get_adjustment_contrast;
var adjustment_enabled: bool setget set_adjustment_enabled, is_adjustment_enabled;
var adjustment_saturation: float setget set_adjustment_saturation, get_adjustment_saturation;
var ambient_light_color: Color setget set_ambient_light_color, get_ambient_light_color;
var ambient_light_energy: float setget set_ambient_light_energy, get_ambient_light_energy;
var ambient_light_occlusion_color: Color setget set_ao_color, get_ao_color;
var ambient_light_sky_contribution: float setget set_ambient_light_sky_contribution, get_ambient_light_sky_contribution;
var ambient_light_source: int setget set_ambient_source, get_ambient_source;
var auto_exposure_enabled: bool setget set_tonemap_auto_exposure_enabled, is_tonemap_auto_exposure_enabled;
var auto_exposure_max_luma: float setget set_tonemap_auto_exposure_max, get_tonemap_auto_exposure_max;
var auto_exposure_min_luma: float setget set_tonemap_auto_exposure_min, get_tonemap_auto_exposure_min;
var auto_exposure_scale: float setget set_tonemap_auto_exposure_grey, get_tonemap_auto_exposure_grey;
var auto_exposure_speed: float setget set_tonemap_auto_exposure_speed, get_tonemap_auto_exposure_speed;
var background_camera_feed_id: int setget set_camera_feed_id, get_camera_feed_id;
var background_canvas_max_layer: int setget set_canvas_max_layer, get_canvas_max_layer;
var background_color: Color setget set_bg_color, get_bg_color;
var background_energy: float setget set_bg_energy, get_bg_energy;
var background_mode: int setget set_background, get_background;
var fog_aerial_perspective: float setget set_fog_aerial_perspective, get_fog_aerial_perspective;
var fog_density: float setget set_fog_density, get_fog_density;
var fog_enabled: bool setget set_fog_enabled, is_fog_enabled;
var fog_height: float setget set_fog_height, get_fog_height;
var fog_height_density: float setget set_fog_height_density, get_fog_height_density;
var fog_light_color: Color setget set_fog_light_color, get_fog_light_color;
var fog_light_energy: float setget set_fog_light_energy, get_fog_light_energy;
var fog_sun_scatter: float setget set_fog_sun_scatter, get_fog_sun_scatter;
var glow_blend_mode: int setget set_glow_blend_mode, get_glow_blend_mode;
var glow_bloom: float setget set_glow_bloom, get_glow_bloom;
var glow_enabled: bool setget set_glow_enabled, is_glow_enabled;
var glow_hdr_luminance_cap: float setget set_glow_hdr_luminance_cap, get_glow_hdr_luminance_cap;
var glow_hdr_scale: float setget set_glow_hdr_bleed_scale, get_glow_hdr_bleed_scale;
var glow_hdr_threshold: float setget set_glow_hdr_bleed_threshold, get_glow_hdr_bleed_threshold;
var glow_intensity: float setget set_glow_intensity, get_glow_intensity;
var glow_levels/1: float setget set_glow_level, get_glow_level;
var glow_levels/2: float setget set_glow_level, get_glow_level;
var glow_levels/3: float setget set_glow_level, get_glow_level;
var glow_levels/4: float setget set_glow_level, get_glow_level;
var glow_levels/5: float setget set_glow_level, get_glow_level;
var glow_levels/6: float setget set_glow_level, get_glow_level;
var glow_levels/7: float setget set_glow_level, get_glow_level;
var glow_mix: float setget set_glow_mix, get_glow_mix;
var glow_normalized: bool setget set_glow_normalized, is_glow_normalized;
var glow_strength: float setget set_glow_strength, get_glow_strength;
var reflected_light_source: int setget set_reflection_source, get_reflection_source;
var sdfgi_bounce_feedback: float setget set_sdfgi_bounce_feedback, get_sdfgi_bounce_feedback;
var sdfgi_cascade0_distance: float setget set_sdfgi_cascade0_distance, get_sdfgi_cascade0_distance;
var sdfgi_cascades: int setget set_sdfgi_cascades, get_sdfgi_cascades;
var sdfgi_enabled: bool setget set_sdfgi_enabled, is_sdfgi_enabled;
var sdfgi_energy: float setget set_sdfgi_energy, get_sdfgi_energy;
var sdfgi_max_distance: float setget set_sdfgi_max_distance, get_sdfgi_max_distance;
var sdfgi_min_cell_size: float setget set_sdfgi_min_cell_size, get_sdfgi_min_cell_size;
var sdfgi_normal_bias: float setget set_sdfgi_normal_bias, get_sdfgi_normal_bias;
var sdfgi_probe_bias: float setget set_sdfgi_probe_bias, get_sdfgi_probe_bias;
var sdfgi_read_sky_light: bool setget set_sdfgi_read_sky_light, is_sdfgi_reading_sky_light;
var sdfgi_use_occlusion: bool setget set_sdfgi_use_occlusion, is_sdfgi_using_occlusion;
var sdfgi_y_scale: int setget set_sdfgi_y_scale, get_sdfgi_y_scale;
var sky: Sky setget set_sky, get_sky;
var sky_custom_fov: float setget set_sky_custom_fov, get_sky_custom_fov;
var sky_rotation: Vector3 setget set_sky_rotation, get_sky_rotation;
var ss_reflections_depth_tolerance: float setget set_ssr_depth_tolerance, get_ssr_depth_tolerance;
var ss_reflections_enabled: bool setget set_ssr_enabled, is_ssr_enabled;
var ss_reflections_fade_in: float setget set_ssr_fade_in, get_ssr_fade_in;
var ss_reflections_fade_out: float setget set_ssr_fade_out, get_ssr_fade_out;
var ss_reflections_max_steps: int setget set_ssr_max_steps, get_ssr_max_steps;
var ssao_ao_channel_affect: float setget set_ssao_ao_channel_affect, get_ssao_ao_channel_affect;
var ssao_detail: float setget set_ssao_detail, get_ssao_detail;
var ssao_enabled: bool setget set_ssao_enabled, is_ssao_enabled;
var ssao_horizon: float setget set_ssao_horizon, get_ssao_horizon;
var ssao_intensity: float setget set_ssao_intensity, get_ssao_intensity;
var ssao_light_affect: float setget set_ssao_direct_light_affect, get_ssao_direct_light_affect;
var ssao_power: float setget set_ssao_power, get_ssao_power;
var ssao_radius: float setget set_ssao_radius, get_ssao_radius;
var ssao_sharpness: float setget set_ssao_sharpness, get_ssao_sharpness;
var tonemap_exposure: float setget set_tonemap_exposure, get_tonemap_exposure;
var tonemap_mode: int setget set_tonemapper, get_tonemapper;
var tonemap_white: float setget set_tonemap_white, get_tonemap_white;
var volumetric_fog_density: float setget set_volumetric_fog_density, get_volumetric_fog_density;
var volumetric_fog_detail_spread: float setget set_volumetric_fog_detail_spread, get_volumetric_fog_detail_spread;
var volumetric_fog_enabled: bool setget set_volumetric_fog_enabled, is_volumetric_fog_enabled;
var volumetric_fog_gi_inject: float setget set_volumetric_fog_gi_inject, get_volumetric_fog_gi_inject;
var volumetric_fog_length: float setget set_volumetric_fog_length, get_volumetric_fog_length;
var volumetric_fog_light: Color setget set_volumetric_fog_light, get_volumetric_fog_light;
var volumetric_fog_light_energy: float setget set_volumetric_fog_light_energy, get_volumetric_fog_light_energy;
var volumetric_fog_temporal_reprojection_amount: float setget set_volumetric_fog_temporal_reprojection_amount, get_volumetric_fog_temporal_reprojection_amount;
var volumetric_fog_temporal_reprojection_enabled: bool setget set_volumetric_fog_temporal_reprojection_enabled, is_volumetric_fog_temporal_reprojection_enabled;

func get_glow_level(idx: int) -> float:
    pass;

func set_glow_level(idx: int, intensity: float) -> void:
    pass;

