extends Resource
class_name Environment
const BG_CLEAR_COLOR = 0;
const BG_COLOR = 1;
const BG_SKY = 2;
const BG_CANVAS = 3;
const BG_KEEP = 4;
const BG_CAMERA_FEED = 5;
const BG_MAX = 6;
const AMBIENT_SOURCE_BG = 0;
const AMBIENT_SOURCE_DISABLED = 1;
const AMBIENT_SOURCE_COLOR = 2;
const AMBIENT_SOURCE_SKY = 3;
const REFLECTION_SOURCE_BG = 0;
const REFLECTION_SOURCE_DISABLED = 1;
const REFLECTION_SOURCE_SKY = 2;
const TONE_MAPPER_LINEAR = 0;
const TONE_MAPPER_REINHARDT = 1;
const TONE_MAPPER_FILMIC = 2;
const TONE_MAPPER_ACES = 3;
const GLOW_BLEND_MODE_ADDITIVE = 0;
const GLOW_BLEND_MODE_SCREEN = 1;
const GLOW_BLEND_MODE_SOFTLIGHT = 2;
const GLOW_BLEND_MODE_REPLACE = 3;
const GLOW_BLEND_MODE_MIX = 4;
const SDFGI_CASCADES_4 = 0;
const SDFGI_CASCADES_6 = 1;
const SDFGI_CASCADES_8 = 2;
const SDFGI_Y_SCALE_DISABLED = 0;
const SDFGI_Y_SCALE_75_PERCENT = 1;
const SDFGI_Y_SCALE_50_PERCENT = 2;
const VOLUMETRIC_FOG_SHADOW_FILTER_DISABLED = 0;
const VOLUMETRIC_FOG_SHADOW_FILTER_LOW = 1;
const VOLUMETRIC_FOG_SHADOW_FILTER_MEDIUM = 2;
const VOLUMETRIC_FOG_SHADOW_FILTER_HIGH = 3;

var adjustment_brightness: float;
var adjustment_color_correction: Texture;
var adjustment_contrast: float;
var adjustment_enabled: bool;
var adjustment_saturation: float;
var ambient_light_color: Color;
var ambient_light_energy: float;
var ambient_light_occlusion_color: Color;
var ambient_light_sky_contribution: float;
var ambient_light_source: int;
var auto_exposure_enabled: bool;
var auto_exposure_max_luma: float;
var auto_exposure_min_luma: float;
var auto_exposure_scale: float;
var auto_exposure_speed: float;
var background_camera_feed_id: int;
var background_canvas_max_layer: int;
var background_color: Color;
var background_energy: float;
var background_mode: int;
var fog_aerial_perspective: float;
var fog_density: float;
var fog_enabled: bool;
var fog_height: float;
var fog_height_density: float;
var fog_light_color: Color;
var fog_light_energy: float;
var fog_sun_scatter: float;
var glow_blend_mode: int;
var glow_bloom: float;
var glow_enabled: bool;
var glow_hdr_luminance_cap: float;
var glow_hdr_scale: float;
var glow_hdr_threshold: float;
var glow_intensity: float;
var glow_levels/1: float;
var glow_levels/2: float;
var glow_levels/3: float;
var glow_levels/4: float;
var glow_levels/5: float;
var glow_levels/6: float;
var glow_levels/7: float;
var glow_mix: float;
var glow_normalized: bool;
var glow_strength: float;
var reflected_light_source: int;
var sdfgi_bounce_feedback: float;
var sdfgi_cascade0_distance: float;
var sdfgi_cascades: int;
var sdfgi_enabled: bool;
var sdfgi_energy: float;
var sdfgi_max_distance: float;
var sdfgi_min_cell_size: float;
var sdfgi_normal_bias: float;
var sdfgi_probe_bias: float;
var sdfgi_read_sky_light: bool;
var sdfgi_use_occlusion: bool;
var sdfgi_y_scale: int;
var sky: Sky;
var sky_custom_fov: float;
var sky_rotation: Vector3;
var ss_reflections_depth_tolerance: float;
var ss_reflections_enabled: bool;
var ss_reflections_fade_in: float;
var ss_reflections_fade_out: float;
var ss_reflections_max_steps: int;
var ssao_ao_channel_affect: float;
var ssao_detail: float;
var ssao_enabled: bool;
var ssao_horizon: float;
var ssao_intensity: float;
var ssao_light_affect: float;
var ssao_power: float;
var ssao_radius: float;
var ssao_sharpness: float;
var tonemap_exposure: float;
var tonemap_mode: int;
var tonemap_white: float;
var volumetric_fog_density: float;
var volumetric_fog_detail_spread: float;
var volumetric_fog_enabled: bool;
var volumetric_fog_gi_inject: float;
var volumetric_fog_length: float;
var volumetric_fog_light: Color;
var volumetric_fog_light_energy: float;
var volumetric_fog_temporal_reprojection_amount: float;
var volumetric_fog_temporal_reprojection_enabled: bool;

func get_glow_level(idx: int) -> float:
    pass;
func set_glow_level(idx: int, intensity: float) -> void:
    pass;
