# Auto-generated SCons stubs
# Simplified for IDE code completion
from typing import Any

# <class 'int'>
% Stack boTTom %: Any = ...

# <class 'list'>
ARGLIST: Any = ...

# <class 'dict'>
ARGUMENTS: Any = ...

# SCons.Action
def Action(*args, **kwargs): ...

# SCons.Util.envs
def AddMethod(*args, **kwargs): ...

# SCons.Script.Main
def AddOption(*args, **kwargs): ...

# SCons.Script.SConscript
def AddPostAction(*args, **kwargs): ...

# SCons.Script.SConscript
def AddPreAction(*args, **kwargs): ...

# SCons.Script.SConscript
def Alias(*args, **kwargs): ...

# SCons.Subst
def AllowSubstExceptions(*args, **kwargs): ...

# SCons.Script.SConscript
def AlwaysBuild(*args, **kwargs): ...

# SCons.Script
BUILD_TARGETS: Any = ...

# SCons.Variables.BoolVariable
def BoolVariable(*args, **kwargs): ...

# SCons.Script.Main
BuildTask: Any = ...

# SCons.Builder
def Builder(*args, **kwargs): ...

# SCons.Script.SConscript
def CFile(*args, **kwargs): ...

# <class 'list'>
COMMAND_LINE_TARGETS: Any = ...

# SCons.Scanner
def CScan(*args, **kwargs): ...

# SCons.Scanner
def CScanner(*args, **kwargs): ...

# SCons.Script.SConscript
def CXXFile(*args, **kwargs): ...

# SCons.Script.SConscript
def CacheDir(*args, **kwargs): ...

# SCons.Action
def Chmod(*args, **kwargs): ...

# SCons.Script.SConscript
def Clean(*args, **kwargs): ...

# SCons.Script.Main
CleanTask: Any = ...

# SCons.Script.SConscript
def Command(*args, **kwargs): ...

# SCons.Script.SConscript
def Configure(*args, **kwargs): ...

# SCons.Action
def Copy(*args, **kwargs): ...

# <class 'list'>
DEFAULT_TARGETS: Any = ...

# SCons.Scanner.D
def DScanner(*args, **kwargs): ...

# SCons.Script.SConscript
def DVI(*args, **kwargs): ...

# SCons.Script.Main
def DebugOptions(*args, **kwargs): ...

# SCons.Script.SConscript
def Decider(*args, **kwargs): ...

# SCons.Script.SConscript
def Default(*args, **kwargs): ...

# SCons.Defaults
def DefaultEnvironment(*args, **kwargs): ...

# SCons.Action
def Delete(*args, **kwargs): ...

# SCons.Script.SConscript
def Depends(*args, **kwargs): ...

# SCons.Script.SConscript
def Dir(*args, **kwargs): ...

# SCons.Scanner
def DirScanner(*args, **kwargs): ...

# SCons.Script.SConscript
def EnsurePythonVersion(*args, **kwargs): ...

# SCons.Script.SConscript
def EnsureSConsVersion(*args, **kwargs): ...

# SCons.Script.SConscript
def Entry(*args, **kwargs): ...

# SCons.Variables.EnumVariable
def EnumVariable(*args, **kwargs): ...

# SCons.Script.SConscript
Environment: Any = ...

# SCons.Script.SConscript
def Execute(*args, **kwargs): ...

# SCons.Script.SConscript
def Exit(*args, **kwargs): ...

# SCons.Script.SConscript
def Export(*args, **kwargs): ...

# SCons.Script.SConscript
def File(*args, **kwargs): ...

# SCons.Script.SConscript
def FindFile(*args, **kwargs): ...

# SCons.Script.SConscript
def FindInstalledFiles(*args, **kwargs): ...

# SCons.Scanner
FindPathDirs: Any = ...

# SCons.Script.SConscript
def FindSourceFiles(*args, **kwargs): ...

# SCons.Script.SConscript
def Flatten(*args, **kwargs): ...

# SCons.Script.Main
def GetBuildFailures(*args, **kwargs): ...

# SCons.Script.SConscript
def GetBuildPath(*args, **kwargs): ...

# SCons.Script.SConscript
def GetLaunchDir(*args, **kwargs): ...

# SCons.Script.Main
def GetOption(*args, **kwargs): ...

# SCons.Script.SConscript
def GetSConsVersion(*args, **kwargs): ...

# SCons.Script.SConscript
def Glob(*args, **kwargs): ...

# <class 'list'>
GlobalDefaultBuilders: Any = ...

# <class 'list'>
GlobalDefaultEnvironmentFunctions: Any = ...

# SCons.Script.SConscript
def Help(*args, **kwargs): ...

# SCons.Script
def HelpFunction(*args, **kwargs): ...

# SCons.Script.SConscript
def Ignore(*args, **kwargs): ...

# SCons.Script.SConscript
def Import(*args, **kwargs): ...

# SCons.Script.SConscript
def Install(*args, **kwargs): ...

# SCons.Script.SConscript
def InstallAs(*args, **kwargs): ...

# SCons.Script.SConscript
def InstallVersionedLib(*args, **kwargs): ...

# SCons.Script.SConscript
def Jar(*args, **kwargs): ...

# SCons.Script.SConscript
def Java(*args, **kwargs): ...

# SCons.Script.SConscript
def JavaH(*args, **kwargs): ...

# SCons.Script.SConscript
def Library(*args, **kwargs): ...

# SCons.Variables.ListVariable
def ListVariable(*args, **kwargs): ...

# SCons.Script.SConscript
def Literal(*args, **kwargs): ...

# SCons.Script.SConscript
def LoadableModule(*args, **kwargs): ...

# SCons.Script.SConscript
def Local(*args, **kwargs): ...

# SCons.Script.SConscript
def M4(*args, **kwargs): ...

# SCons.Script.SConscript
def MSVSProject(*args, **kwargs): ...

# SCons.Action
def Mkdir(*args, **kwargs): ...

# SCons.Action
def Move(*args, **kwargs): ...

# SCons.Script.SConscript
def NoCache(*args, **kwargs): ...

# SCons.Script.SConscript
def NoClean(*args, **kwargs): ...

# SCons.Script.SConscript
def Object(*args, **kwargs): ...

# SCons.Script.SConscript
def PCH(*args, **kwargs): ...

# SCons.Script.SConscript
def PDF(*args, **kwargs): ...

# SCons.Script.SConscript
def Package(*args, **kwargs): ...

# SCons.Variables.PackageVariable
def PackageVariable(*args, **kwargs): ...

# SCons.Script.SConscript
def ParseDepends(*args, **kwargs): ...

# SCons.Variables.PathVariable
def PathVariable(*args, **kwargs): ...

# SCons.Platform
def Platform(*args, **kwargs): ...

# SCons.Script.SConscript
def PostScript(*args, **kwargs): ...

# SCons.Script.SConscript
def Precious(*args, **kwargs): ...

# SCons.Script.Main
def PrintHelp(*args, **kwargs): ...

# SCons.Script.SConscript
def Program(*args, **kwargs): ...

# SCons.Scanner
def ProgramScanner(*args, **kwargs): ...

# SCons.Script.Main
def Progress(*args, **kwargs): ...

# SCons.Script.SConscript
def Pseudo(*args, **kwargs): ...

# SCons.Script.SConscript
def PyPackageDir(*args, **kwargs): ...

# SCons.Script.Main
QuestionTask: Any = ...

# SCons.Script.SConscript
def RES(*args, **kwargs): ...

# SCons.Script.SConscript
def RMIC(*args, **kwargs): ...

# SCons.Script.SConscript
def Repository(*args, **kwargs): ...

# SCons.Script.SConscript
def Requires(*args, **kwargs): ...

# SCons.Script.SConscript
def Return(*args, **kwargs): ...

# SCons.Script.SConscript
def SConscript(*args, **kwargs): ...

# SCons.Script.SConscript
def SConscriptChdir(*args, **kwargs): ...

# SCons.Script.SConscript
def SConsignFile(*args, **kwargs): ...

# SCons.Scanner
Scanner: Any = ...

# SCons.Script.Main
def SetOption(*args, **kwargs): ...

# SCons.Script.SConscript
def SharedLibrary(*args, **kwargs): ...

# SCons.Script.SConscript
def SharedObject(*args, **kwargs): ...

# SCons.Script.SConscript
def SideEffect(*args, **kwargs): ...

# SCons.Scanner
def SourceFileScanner(*args, **kwargs): ...

# SCons.Script.SConscript
def Split(*args, **kwargs): ...

# SCons.Script.SConscript
def StaticLibrary(*args, **kwargs): ...

# SCons.Script.SConscript
def StaticObject(*args, **kwargs): ...

# _io
StringIO: Any = ...

# SCons.Script.SConscript
def Substfile(*args, **kwargs): ...

# <class 'bool'>
TYPE_CHECKING: Any = ...

# SCons.Script.SConscript
def Tag(*args, **kwargs): ...

# SCons.Script.SConscript
def Tar(*args, **kwargs): ...

# SCons.Script
TargetList: Any = ...

# SCons.Script.SConscript
def Textfile(*args, **kwargs): ...

# SCons.Tool
Tool: Any = ...

# SCons.Action
def Touch(*args, **kwargs): ...

# SCons.Script.SConscript
def TypeLibrary(*args, **kwargs): ...

# SCons.Script.Main
def ValidateOptions(*args, **kwargs): ...

# SCons.Script.SConscript
def Value(*args, **kwargs): ...

# SCons.Script
def Variables(*args, **kwargs): ...

# SCons.Script.SConscript
def VariantDir(*args, **kwargs): ...

# SCons.Platform.virtualenv
def Virtualenv(*args, **kwargs): ...

# SCons.Util
def WhereIs(*args, **kwargs): ...

# SCons.Script.SConscript
def Zip(*args, **kwargs): ...

# <class 'list'>
call_stack: Any = ...

# <class 'NoneType'>
help_text: Any = ...

# <class 'module'>
json: Any = ...

# SCons.Script.Main
def main(*args, **kwargs): ...

# <class 'module'>
os: Any = ...

# <class 'int'>
sconscript_reading: Any = ...

# SCons.Script
def set_missing_sconscript_error(*args, **kwargs): ...

# <class 'dict'>
snapshot: Any = ...

# <class 'float'>
start_time: Any = ...

# <class 'module'>
sys: Any = ...

