"""Generate godot-cpp bindings and their checked-in build metadata.

Used as a part of Bazel. It is also used to regenerate `.gdextension` and
`godot_cpp_generated_files.bzl` based on `godot_version.bzl` file.
For regeneration use `--regenerate-metadata`, to only verify that the committed
metadata is up to date use `--check-metadata` (see the `metadata_test` Bazel target).
"""

import argparse
import difflib
import re
import sys
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parent
VENDORED_GODOT_CPP_DIR = ROOT_DIR / "thirdParty" / "godot-cpp"
if VENDORED_GODOT_CPP_DIR.is_dir():
    sys.path.insert(0, str(VENDORED_GODOT_CPP_DIR))

from binding_generator import generate_bindings, get_file_list


VERSION_FILE = ROOT_DIR / "godot_version.bzl"
GENERATED_FILES_BZL = ROOT_DIR / "godot_cpp_generated_files.bzl"
GDEXTENSION_FILE = ROOT_DIR / "project" / "addons" / "godot-rd" / "bin" / "godot-rd.gdextension"
VERSION_PATTERN = re.compile(r'^GODOT_VERSION = "([0-9]+\.[0-9]+)"$', re.MULTILINE)


def read_godot_version() -> str:
    matches = VERSION_PATTERN.findall(VERSION_FILE.read_text(encoding="utf-8"))
    if len(matches) != 1:
        raise ValueError(f"{VERSION_FILE} must contain exactly one GODOT_VERSION assignment")
    return matches[0]


def render_list(name: str, values: list[str]) -> str:
    lines = [f"{name} = ["]
    lines.extend(f'    "{value}",' for value in values)
    lines.append("]")
    return "\n".join(lines)


def default_api_file(version: str) -> Path:
    return VENDORED_GODOT_CPP_DIR / "gdextension" / f"extension_api-{version.replace('.', '-')}.json"


def render_generated_files_bzl(version: str, api_file: Path) -> str:
    if not api_file.is_file():
        raise FileNotFoundError(f"Godot extension API file does not exist: {api_file}")

    generated_files = get_file_list(
        api_filepath=str(api_file),
        output_dir=".",
        headers=True,
        sources=True,
    )
    headers = sorted(path for path in generated_files if path.endswith((".h", ".hpp", ".inc")))
    sources = sorted(path for path in generated_files if path.endswith(".cpp"))
    if len(headers) + len(sources) != len(generated_files):
        raise ValueError("The godot-cpp generator returned a file with an unsupported extension")

    return f'''"""Auto-generated list of files produced by godot-cpp's binding_generator.py.

Do NOT edit by hand. Regenerate with:
    python3 godot_cpp_gen_main.py --regenerate-metadata
The API version comes from godot_version.bzl (currently {version}, i.e.
gdextension/extension_api-{version.replace('.', '-')}.json).
"""

{render_list("GODOT_CPP_GENERATED_HEADERS", headers)}

{render_list("GODOT_CPP_GENERATED_SOURCES", sources)}
'''


def render_gdextension(version: str) -> str:
    return f'''; Generated by godot_cpp_gen_main.py from godot_version.bzl. Do not edit by hand.
; Regenerate with:
;   python3 godot_cpp_gen_main.py --regenerate-metadata

[configuration]

entry_symbol = "dynamic_entry"
compatibility_minimum = "{version}"
reloadable = true

[libraries]
; Relative paths ensure that our GDExtension can be placed anywhere in the project directory.
macos.arm64.single.debug = "./macos/godot-rd.macos.arm64.dylib"
macos.x86_64.single.debug = "./macos/godot-rd.macos.x86_64.dylib"

windows.x86_64.single.debug = "./windows/godot-rd.windows.x86_64.dll"
windows.arm64.single.debug = "./windows/godot-rd.windows.arm64.dll"

linux.x86_64.single.debug = "./linux/godot-rd.linux.x86_64.so"
linux.arm64.single.debug = "./linux/godot-rd.linux.arm64.so"
'''


def render_metadata(version: str, api_file: Path) -> dict[Path, str]:
    return {
        GENERATED_FILES_BZL: render_generated_files_bzl(version, api_file),
        GDEXTENSION_FILE: render_gdextension(version),
    }


def regenerate_metadata(metadata: dict[Path, str]) -> None:
    for path, content in metadata.items():
        path.write_text(content, encoding="utf-8")
        print(f"Regenerated {path}")


def check_metadata(metadata: dict[Path, str]) -> int:
    stale = []
    for path, expected in metadata.items():
        committed = path.read_text(encoding="utf-8") if path.is_file() else ""
        if committed == expected:
            continue
        stale.append(path.name)
        sys.stdout.writelines(difflib.unified_diff(
            committed.splitlines(keepends=True),
            expected.splitlines(keepends=True),
            fromfile=f"{path.name} (committed)",
            tofile=f"{path.name} (generated)",
        ))
    if stale:
        print(
            f"\nThe committed {', '.join(stale)} is out of date. "
            "Regenerate it with `python3 godot_cpp_gen_main.py --regenerate-metadata` and commit the result."
        )
        return 1
    print("The committed godot-cpp build metadata is up to date")
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate godot-cpp bindings or their checked-in build metadata.",
    )
    parser.add_argument(
        "--regenerate-metadata",
        action="store_true",
        help="regenerate godot_cpp_generated_files.bzl and godot-rd.gdextension",
    )
    parser.add_argument(
        "--check-metadata",
        action="store_true",
        help="fail if the committed godot_cpp_generated_files.bzl or godot-rd.gdextension differs from the generated one",
    )
    parser.add_argument("--api-filepath")
    parser.add_argument("--interface-filepath")
    parser.add_argument("--use-template-get-node", default="True")
    parser.add_argument("--bits", default="64")
    parser.add_argument("--precision", default="single")
    parser.add_argument("--output-dir", default=".")
    args = parser.parse_args()

    if args.regenerate_metadata or args.check_metadata:
        version = read_godot_version()
        api_file = Path(args.api_filepath) if args.api_filepath else default_api_file(version)
        metadata = render_metadata(version, api_file)
        if args.check_metadata:
            sys.exit(check_metadata(metadata))
        regenerate_metadata(metadata)
        return

    if not args.api_filepath or not args.interface_filepath:
        parser.error("--api-filepath and --interface-filepath are required when generating bindings")

    generate_bindings(
        api_filepath=args.api_filepath,
        interface_filepath=args.interface_filepath,
        use_template_get_node=args.use_template_get_node,
        bits=args.bits,
        precision=args.precision,
        output_dir=args.output_dir,
    )


if __name__ == "__main__":
    main()
