package gdscript.polySymbols.sdk

import com.intellij.navigation.SymbolNavigationService
import com.intellij.openapi.project.Project
import com.intellij.openapi.util.Key
import com.intellij.platform.backend.navigation.NavigationTarget
import com.intellij.polySymbols.PolySymbol
import com.intellij.polySymbols.refactoring.PolySymbolRenameTarget
import com.intellij.polySymbols.search.PolySymbolSearchTarget
import com.intellij.psi.PsiElement
import com.intellij.psi.util.PsiTreeUtil
import gdscript.polySymbols.GdIsEngineSymbolProperty
import gdscript.polySymbols.GdNavigationElementProperty
import gdscript.polySymbols.GdPolySymbol
import gdscript.polySymbols.index.GdPolySymbolQueriesUtil
import gdscript.polySymbols.sdk.xml.GdSdkData
import gdscript.psi.GdNamedElement

abstract class GdSdkPolySymbol : GdPolySymbol() {

    companion object {
        /**
         * User data key placed on synthetic GdScript files generated by [GdSdkPolySymbol.getNavigationTargets].
         * The value is the declaring class name (e.g. "Node2D").
         */
        val SYNTHETIC_SDK_CLASS_KEY: Key<String> = Key.create("GdSdk.SyntheticFileClassName")
    }

    abstract val data: GdSdkData?
    protected abstract val project: Project

    override val searchTarget: PolySymbolSearchTarget?
        get() = PolySymbolSearchTarget.create(this)

    override fun getNavigationTargets(project: Project): Collection<NavigationTarget> {
        // when the class is found in the SDK, we navigate to a generated gdscript file
        val target = syntheticSourceElement(project) ?: return emptyList()
        return listOf(SymbolNavigationService.getInstance().psiElementNavigationTarget(target))
    }

    /**
     * The generated gdscript file's matching element for this symbol, or the file itself as a
     * fallback when no matching element exists - or `null` when the SDK class this symbol belongs
     * to can't be found at all.
     */
    open fun syntheticSourceElement(project: Project): PsiElement? {
        val classData = getOwnerClassData() ?: return null

        val syntheticFile = GdSdkSyntheticPsiCache.getInstance(project)
            .getOrCreateSyntheticFile(declaringClassId, classData)
        return PsiTreeUtil.findChildrenOfType(syntheticFile, GdNamedElement::class.java)
            .find { psiElementRepresentsSdkSymbol(it) }
            ?: syntheticFile
    }

    @PolySymbol.Property(GdNavigationElementProperty::class)
    private val navigationElement: PsiElement? get() = syntheticSourceElement(project)

    @PolySymbol.Property(GdIsEngineSymbolProperty::class)
    private val isEngineSymbol: Boolean get() = true

    /**
     * Used when creating navigation targets for SDK symbols.
     * Returns true if the PSI element is the generated representation of the corresponding SDK symbol.
     */
    open fun psiElementRepresentsSdkSymbol(element: GdNamedElement): Boolean {
        return element.name == name
    }

    override val renameTarget: PolySymbolRenameTarget? get() = null


    private fun getOwnerClassData(): GdSdkData.ClassData? {
        if (this is GdSdkClassSymbol) return data

        return GdPolySymbolQueriesUtil.getSdkClassSymbol(project, declaringClassId)?.data
    }

    protected fun getOwnerClassData(project: Project, className: String): GdSdkData.ClassData? {
        return GdPolySymbolQueriesUtil.getSdkClassSymbol(project, className)?.data
    }
}

