//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "FrontendGodotRoot.h"


#include "FrontendGodotRoot/FrontendGodotRoot.h"
#include "FrontendGodotRoot/FrontendGodotRoot.h"
#include "FrontendGodotModel/FrontendGodotModel.h"

#ifdef _MSC_VER
#pragma warning( push )
#pragma warning( disable:4250 )
#pragma warning( disable:4307 )
#pragma warning( disable:4267 )
#pragma warning( disable:4244 )
#pragma warning( disable:4100 )
#endif

namespace JetBrains {
namespace GodotPlugin {
// companion

FrontendGodotRoot::FrontendGodotRootSerializersOwner const FrontendGodotRoot::serializersOwner;

void FrontendGodotRoot::FrontendGodotRootSerializersOwner::registerSerializersCore(rd::Serializers const& serializers) const
{
    FrontendGodotModel::serializersOwner.registry(serializers);
}

void FrontendGodotRoot::connect(rd::Lifetime lifetime, rd::IProtocol const * protocol)
{
    FrontendGodotRoot::serializersOwner.registry(protocol->get_serializers());
    
    identify(*(protocol->get_identity()), rd::RdId::Null().mix("FrontendGodotRoot"));
    bind(lifetime, protocol, "FrontendGodotRoot");
}

// constants
// initializer
void FrontendGodotRoot::initialize()
{
    serializationHash = 3824044970806178095L;
}
// primary ctor
// secondary constructor
// default ctors and dtors
FrontendGodotRoot::FrontendGodotRoot()
{
    initialize();
}
// reader
// writer
// virtual init
void FrontendGodotRoot::init(rd::Lifetime lifetime) const
{
    rd::RdExtBase::init(lifetime);
}
// identify
void FrontendGodotRoot::identify(const rd::Identities &identities, rd::RdId const &id) const
{
    rd::RdBindableBase::identify(identities, id);
}
// getters
// intern
// equals trait
// equality operators
bool operator==(const FrontendGodotRoot &lhs, const FrontendGodotRoot &rhs) {
    return &lhs == &rhs;
}
bool operator!=(const FrontendGodotRoot &lhs, const FrontendGodotRoot &rhs){
    return !(lhs == rhs);
}
// hash code trait
// type name trait
// static type name trait
// polymorphic to string
std::string FrontendGodotRoot::toString() const
{
    std::string res = "FrontendGodotRoot\n";
    return res;
}
// external to string
std::string to_string(const FrontendGodotRoot & value)
{
    return value.toString();
}
}
}

#ifdef _MSC_VER
#pragma warning( pop )
#endif

