# For syntax, see https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax
# This workflow is automatically triggered for pull requests to verify that everything still builds.

name: Editor Plugin Tests
on:
  pull_request:
  merge_group:
  workflow_dispatch:

env:

  # Used to select the version of Godot to run the tests with.
  GODOT_TEST_VERSION: 4.6.1-stable
  # Use UTF-8 on Linux.
  LANG: en_US.UTF-8
  LC_ALL: en_US.UTF-8
  # Use UTF-8 on Windows.
  PYTHONIOENCODING: utf8

defaults:
  run:
    working-directory: godot-editor-addon

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # Test a few selected combinations of parameters ("test case matrix").
        include:
          - target: { platform: linux, arch: x86_64, os: ubuntu-22.04, run-tests: true }
            float-precision: single
          - target: { platform: windows, arch: x86_64, os: windows-latest, run-tests: false }
            float-precision: single
          - target: { platform: macos, arch: universal, os: macos-latest, run-tests: false }
            float-precision: single

    runs-on: ${{ matrix.target.os }}
    env:
      SCCACHE_GHA_ENABLED: "true"
    steps:
      # Clone this repository
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: true

      # Setup dependencies
      - name: Setup godot-cpp
        uses: ./godot-editor-addon/native/rider-plugin/godot-cpp/.github/actions/setup-godot-cpp
        with:
          platform: ${{ matrix.target.platform }}
          buildtool: cmake

      - name: Install minimum supported CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "3.25.0" # should match the version in the `CMakeLists.txt`

      - name: Run sccache
        uses: mozilla-actions/sccache-action@v0.0.9

      # Build GDExtension
      - name: Configure GDExtension
        run: >
          cmake --preset ninja-release
          -DCMAKE_C_COMPILER_LAUNCHER=sccache
          -DCMAKE_CXX_COMPILER_LAUNCHER=sccache

      - name: Build GDExtension
        run: cmake --build build/ninja-release --verbose

      - name: Download requested Godot version for testing
        if: matrix.target.run-tests
        run: |
          wget "https://github.com/godotengine/godot/releases/download/${GODOT_TEST_VERSION}/Godot_v${GODOT_TEST_VERSION}_linux.x86_64.zip" -O Godot.zip
          unzip -a Godot.zip
          chmod +x "Godot_v${GODOT_TEST_VERSION}_linux.x86_64"
          echo "GODOT=$(pwd)/Godot_v${GODOT_TEST_VERSION}_linux.x86_64" >> $GITHUB_ENV

      - name: Run tests
        if: matrix.target.run-tests
        run: |
          $GODOT --headless --version
          cd native
          ./run-tests.sh
